version: '3.9'

services:
  app:
    build: 
      dockerfile: ./Dockerfile
    container_name: drawingserver
    restart: unless-stopped
    ports:
      - "3000:3000"
    
  db:
    image: mysql:latest
    container_name: drawingdb
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: drawing
      MYSQL_ROOT_PASSWORD: 123321
      MYSQL_USER: dakz
      MYSQL_PASSWORD: 123321
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
