version: '3'

services:
  simple-nginx:
    image: 'nginx:alpine'
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=drawingwss.freemyip.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=drawingwss.freemyip.com
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      
  proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:z,ro
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
      - ./proxy/upload.conf:/etc/nginx/conf.d/uploadsize.conf
      
  letsencrypt-companion:
    image: 'nginxproxy/acme-companion'
    restart: always
    volumes:
      - certs:/etc/nginx/certs:z
      - acme:/etc/acme.sh:z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
    depends_on:
      - proxy

volumes:
  certs:
  acme:
  vhost.d:
  html:
